In [5]:
# Import packages
import numpy as np
from scipy import stats

In [6]:
#Create a list
myList = [20, 2, 7, 1, 2, 34]
print("myList : ",myList)

myList :  [20, 2, 7, 1, 2, 34]


In [7]:
#Mean
print("mean of myList : ",np.mean(myList))

mean of myList :  11.0


In [8]:
#Median
print("median of myList :",np.median(myList))

median of myList : 4.5


In [9]:
#Mode
print("Mode of myList :",stats.mode(myList))

Mode of myList : ModeResult(mode=array([2]), count=array([2]))


In [10]:
#Range
print("Range of myList : ", np.max(myList) - np.min(myList))

Range of myList :  33


In [11]:
#Variance
print("Variance of myList : ", np.var(myList))

Variance of myList :  148.0


In [13]:
#Standard Deviation
print("Standard deviation of myList : ", np.std(myList))

Standard deviation of myList :  12.165525060596439


##  BASIC PYTHON OPERATIONS
This file is for python basic programming 

In [14]:
print("Hello World!")

Hello World!


In [15]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [16]:
#This is a variable
firstVar = 'Hello World!'
print(firstVar)

Hello World!


In [17]:
firstVar

'Hello World!'

In [18]:
firstVar = 'Hello'
secondVal = 'World!'
print(firstVar, secondVal)

Hello World!


In [19]:
firstVar = 'Hi'
secondVal ='How are you'
print(firstVar, secondVal, sep=',')

Hi,How are you


OPERATORS

In [8]:
# ADDITION
15 + 12

27

In [21]:
# STRING ADDITION
'15' + '12'

'1512'

Datatype of Variable

In [22]:
#Indentify string
firstVar = 'Hello World'
type(firstVar)

str

In [23]:
#Identify integer
numVar = 1
type(numVar)

int

In [24]:
#Identify float
numVar = 1.02
type(numVar)

float

In [25]:
# boolean datatype
Var1 = 24
Var2 = 46
ops = Var1 < Var2
print(ops)
type(ops)

True


bool

In [16]:
#Storing multiple values - List
myList = [1, "Hello,55.6,True"]
print(myList)
type(myList)


[1, 'Hello,55.6,True']


list

In [26]:
#Accessing list values
myList[2]

7

In [27]:
# Indicating tuple and its type
myTuple = ("Red","Blue","Green")
print(myTuple)
type(myTuple)

('Red', 'Blue', 'Green')


tuple

In [28]:
print(myTuple[1])

Blue


In [29]:
myList

[20, 2, 7, 1, 2, 34]

In [30]:
myList[1]='Hi'

In [31]:
myList

[20, 'Hi', 7, 1, 2, 34]

In [32]:
myTuple[1]

'Blue'

In [33]:
myTuple

('Red', 'Blue', 'Green')

In [34]:
myDict = {"empName":"Akshay","age":21}
print(myDict)
type(myDict)

{'empName': 'Akshay', 'age': 21}


dict

In [36]:
# Access dict with key
print(myDict['empName'])

Akshay


In [37]:
#Defining multiple values in Dict
keyValue = {"empName":["Akshay","Shweta","David","Mary"], "age": [24,21,26,22]}
type(keyValue)

dict

In [38]:
print(keyValue['empName'])

['Akshay', 'Shweta', 'David', 'Mary']


In [39]:
#Accessing List within Dict
print(keyValue['empName'][2])

David


PLACEHOLDER

In [40]:
#Placeholder
name = "David"
age = 26
print("Name is %s and age is %d" %(name,age))

Name is David and age is 26


In [41]:
print("Name is", name,"and age is",age)

Name is David and age is 26


TYPE CASTING/CONVERTING DATA TYPE

In [42]:
var1 = '10'
type(var1)

str

In [43]:
var2 = 30
type(var2)

int

In [44]:
#Add
int(var1)+(var2)

40

In [45]:
float(10)

10.0

In [46]:
# Converting string to float
var2 = '10.6'
newVar2 = float(var2)
type(newVar2)

float

In [47]:
newVar2

10.6

In [48]:
#Converting tuple to list
newVar3 = ("Red","Blue","Green")
print(newVar3)
type(newVar3)

('Red', 'Blue', 'Green')


tuple

In [49]:
newVar4 = list(newVar3)
type(newVar4)

list

##DECISION MAKING

In [50]:
balance = 2000
if balance == 2000:
   print("spend the money")
else:
    print(" Save it")

spend the money


In [51]:
balance = 2460
if balance > 2000:
    print("Balance is high")
elif balance < 2000:
    print("Balance is low")
else:
    print("No idea")

Balance is high


In [59]:
#Nested elseif statements
balance = 2600
if(balance > 2000):
    if (balance == 2100):
    print("Balance is equal to 2100")
elif(balance > 2500):
    print("Balance is greater than 2500")
else:
    print("Balance is less or equal to 2500")
elif(balance > 1000):
    print("Balance greater than 1000")
elif(balance == 1000):
    print("Balance equals 1000")
    else:
        print("Save it")

IndentationError: expected an indented block (<ipython-input-59-7b2303da0edd>, line 5)

## Loops

In [60]:
# For Loop
for i in [22,33,44]:
    print(i)

22
33
44


In [61]:
for i in range(1,11):
    print (i+5)

6
7
8
9
10
11
12
13
14
15


In [62]:
for i in ['a','b','c']:
    print(i)

a
b
c


In [63]:
lis=[]
for i in range(1,6):
    lis.append(i)

    print(lis)

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]


In [64]:
list1 = ['a','b','c']
for k,v in enumerate(list1):
    print('key:' ,k, 'value:',v)

key: 0 value: a
key: 1 value: b
key: 2 value: c


In [65]:
#While Loop
counter = 5
while counter > 0:
    print('counter =', counter)
    counter = counter-1

counter = 5
counter = 4
counter = 3
counter = 2
counter = 1


# READING INPUTS

In [67]:
balance = input("Enter your balance: ")
balance = int(balance) # Because return type from input

if(balance > 1900):
    if(balance == 2000):
        print("Balance is equal to 2000")
        elif(balance > 2500):
            print("Balance is greater than 2500")
        else:
            print()

SyntaxError: invalid syntax (<ipython-input-67-fda40d53f41b>, line 7)

## EXCEPTION HANDLING

In [68]:
50/0

ZeroDivisionError: division by zero

In [69]:
try:
    answer = 50/0
    print(answer)
except:
        print("You cannot divide a no. by zero")

You cannot divide a no. by zero


In [70]:
try:
    answer = 50/1
    print(answer)
except:
        print(' You cannot diveide a no. by zero')

50.0


## FUNCTIONS

In [72]:
def profile_info(username):
    print("username of the profile is:", username)

In [73]:
profile_info("Sam")

username of the profile is: Sam


In [74]:
def profile_info(username,followers):
    print("Username:", username)
    print("Followers:", followers)

In [75]:
profile_info("Rm","1000")

Username: Rm
Followers: 1000


In [76]:
def profile_info(username,followers=0):
    print("Username:", username)
    print("Followers:",followers)

In [77]:
profile_info("Ram")

Username: Ram
Followers: 0


In [78]:
def profile_default(username,followers=0):
    print("username:", username)
    if(followers > 0):
        print("Followers", followers)

In [79]:
profile_default("Ram")

username: Ram


In [79]:
profile_default("Ram",10)

username: Ram
Followers 10


# CLASS AND OBJECT

In [80]:
# Define class
class shark:
    def swim(self):
        print("shark is swimming")
        
    def be_awesome(self):
        print("shark is being awesome")

In [81]:
#Create object
dobby = shark()

In [82]:
dobby.swim()

shark is swimming


In [83]:
dobby.be_awesome()

shark is being awesome


In [84]:
help(shark())

Help on shark in module __main__ object:

class shark(builtins.object)
 |  Methods defined here:
 |  
 |  be_awesome(self)
 |  
 |  swim(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



CONSTRUCTOR AND DESTRUCTOR

In [85]:
class Vehicle:
    def __init__(self):
        print('Vehicle created, Constructor got called.')  
    def __del__(self):
        print('Destructor called, vehicle deleted')

In [86]:
truck = Vehicle()

Vehicle created, Constructor got called.


In [87]:
del truck

Destructor called, vehicle deleted


# NUMPY BASIC OPERATIONS 19 SEPT 2019

In [88]:
import numpy as np

In [89]:
myList = [1,2,3,4]
print(myList)
type(myList)

[1, 2, 3, 4]


list

In [90]:
arr = np.array(myList)
print(arr)
type(arr)

[1 2 3 4]


numpy.ndarray

list_mu1 = myList * 2
list_mul

In [91]:
list_mu1 = myList * 2
list_mu1

[1, 2, 3, 4, 1, 2, 3, 4]

In [92]:
arr_mul = arr*2
arr_mul

array([2, 4, 6, 8])

In [93]:
arr

array([1, 2, 3, 4])

In [94]:
# No. of dimensions
arr.ndim

1

In [95]:
# convert tuple to array
myTuple = (1,2,3)
print(myTuple)
type(myTuple)

(1, 2, 3)


tuple

In [96]:
arr_tuple = np.array(myTuple)
print(arr_tuple)
type(arr_tuple)

[1 2 3]


numpy.ndarray

In [97]:
# Tuple of array dimension
arr2 = np.array([(1,2,3),(4,5,6)])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr2.ndim

2

In [99]:
#List of array dimension
list1 = [1,2,3]
list2 = [4,5,6]
new_arr = np.array([list1,list2])
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
new_arr.ndim

2

In [101]:
# Item size
new_arr.itemsize

4

In [102]:
#No of elements
new_arr.size

6

In [103]:
#TO check the datatype
new_arr.dtype

dtype('int32')

In [104]:
#Shape
new_arr.shape

(2, 3)

In [105]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
#Reshaping arrays
new_arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
#Transpose an array(only work on top of array)
new_arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [109]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.transpose(new_arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [111]:
arr

array([1, 2, 3, 4])

In [112]:
# Accessing array values
arr[1]

2

In [113]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
new_arr[1,1]

5

In [115]:
#Iterate index values
new_arr[0:,2]

array([3, 6])

In [116]:
new_arr[0:,1:]

array([[2, 3],
       [5, 6]])

In [117]:
n_arr = np.array([(1,2),(3,4),(5,6),(7,8)])
print(n_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [118]:
n_arr[0:,1]

array([2, 4, 6, 8])

In [119]:
n_arr[0:2,1]

array([2, 4])

In [120]:
n_arr[1:3,1]

array([4, 6])

In [121]:
n_arr[1:3]

array([[3, 4],
       [5, 6]])

In [122]:
n_arr[1]

array([3, 4])

In [123]:
#Fetching evenly spaced numbers over a specified interval
e_val = np.linspace(1,3,20)
e_val

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [124]:
#fetch min value
print(arr)
arr.min()

[1 2 3 4]


1

In [125]:
# Fetch max value
arr.max()

4

In [126]:
# sum of values in an array
print(arr)
arr.sum()

[1 2 3 4]


10

In [127]:
print(new_arr)
print("Sum of all the values: ",new_arr.sum())
print("Sum of row values: ",new_arr.sum(axis=1))
print("sum of column values: ",new_arr.sum(axis=0))

[[1 2 3]
 [4 5 6]]
Sum of all the values:  21
Sum of row values:  [ 6 15]
sum of column values:  [5 7 9]


In [128]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
# Getting the square root of all the values
np.sqrt(new_arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [130]:
#To get the square of all the values
new_arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [131]:
#Addition of multiple array elements
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(4,5,6)])
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [132]:
#subtraction of multiple arrays
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [133]:
#Stack arrays - Vertical stacking
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(4,5,6)])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [134]:
#Horizontal Stacking
np.hstack((arr1,arr2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [135]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [136]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [137]:
np.ones(10).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# PANDAS 20 SEPT