# TYPES

In [17]:
# Try your first python output
print('Hello, Python!')

Hello, Python!


In [18]:
# Check the python version
import sys
print(sys.version)

3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]


# TYPES OF OBJECTS IN PYTHON

In [19]:
# Integer
11

11

In [20]:
# Float
2.14

2.14

In [21]:
#String
"Hello Python!"

'Hello Python!'

In [22]:
# Type of 12
type(12)

int

In [23]:
# Type of 2.14
type(2.14)

float

In [24]:
# Type of "Hello, world 2013"
type("Hello, world 2013")

str

In [25]:
# System settings about float type
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

# CONVERTING FROM ONE OBJECT TYPE TO A DIFFERENT OBJECT TYPE

In [26]:
# verify that this is an integer
type(4)

int

# Converting Integers to a float

In [27]:
# convert 2 to a float
float(2)

2.0

In [28]:
# Convert integer 2 to a float to check its type
type(float(3))

float

In [29]:
# Casting 1.1 to integer will result in loss of information
int(1.1)

1

# Converting from strings to integers or floats

In [31]:
# Convert a string into an integer
int('1')

1

In [33]:
# convert a string into an float
float('2.0')

2.0

In [34]:
# converting numbers to string
str(2)

'2'

# BOOLEAN DATA TYPE

In [35]:
# Value true
True

True

In [36]:
# Value false
False

False

In [38]:
# Type of false
type(False)

bool

In [40]:
# Convert TRUE to integer
int(True)

1

In [41]:
# Convert 1 to boolean
bool(1)

True

In [44]:
# Convert 0 to boolean
bool(0)

False

In [45]:
# Convert True to float
float(True)

1.0

# EXPRESSIONS AND VARIABLES
Expressions
Expressions in Python  can include operations compatible types(e.g., integers and floats).For example, basic arithmetic operations like adding mutiple numbers:

In [46]:
#Addition operation expression
43+34+34+50

161

In [47]:
#Subtraction operation expression
69 - 30

39

In [48]:
# Multiplication operation expression
34 * 2

68

In [49]:
# Division operation expression
25/5

5.0

In [50]:
# Division operation expression
25/6

4.166666666666667

In [51]:
# Integer division operation expression
25 // 5

5

In [52]:
# Integer division operation expression
45//6

7

In [53]:
# How many hours there are in 160 minutes
160/60

2.6666666666666665

In [54]:
# Mathematical expression
30 + 2 * 45

120

In [55]:
# Mathematical Expression
(30 + 2) * 40

1280

## VARIABLES

In [57]:
# Store value into variable
x = 43+40+18+70
x

171

In [58]:
x/60

2.85

In [59]:
x*40

6840

In [61]:
x=y=45
y

45

In [62]:
x

45

In [63]:
y/5

9.0

In [66]:
# Name the variables meaningfully
total_min = 43 + 42 + 57 # Total length of albums in minutes
total_min

142

In [68]:
total_hours = total_min / 60 # Total Length of albums in hours
total_hours

2.3666666666666667

In [70]:
# Complicate expression
total_hours = (43 + 42 + 57) / 60 # Total hours in a single expression
total_hours

2.3666666666666667

   #                                                   STRINGS

In [71]:
# Use quotation marks for defining string
"Soumendra Ranjan misra"

'Soumendra Ranjan misra'

In [72]:
# Use single quotation marks for defining string
'Soumendra Ranjan misra'

'Soumendra Ranjan misra'

In [73]:
# Digitals and spaces in string
'1,2,3,4,5'

'1,2,3,4,5'

In [74]:
# Special characters in string
'@#$%^ER'

'@#$%^ER'

In [75]:
# Print the string
print("Hello!")

Hello!


In [82]:
# Assign string to variable
name = "Soumendra Ranjan Misra"
name

'Soumendra Ranjan Misra'

## INDEXING

### POSITIVE INDEXING

In [94]:
# Print the first element in the string
print(name[21])

a


### NEGATIVE INDEXING

In [90]:
print(name[-2])

r


In [91]:
print(name[-3])

s


### Number of characters in a string by using len ,short for length

In [95]:
len("Soumendra Ranjan Misra")

22

In [96]:
len("Soumendra Ranjan Misra")

22

## SLICING

In [98]:
# Take the slice on variable Name with only index 0 to index 3
name[0:4]

'Soum'

In [104]:
# Take the slice on variable  Name with only index 8 to index 11
name[10:16]

'Ranjan'

## STRIDE

In [105]:
# Get every second element. The elements on index 1,3,5....
name[::2]

'SuedaRna ir'

In [108]:
# Get every second element in the range from index 0 to index 4
name[0:5:3]

'Sm'

## CONCATENATE STRINGS

In [112]:
# Concatenate two strings

Statement = name + " is the best "
Statement

'Soumendra Ranjan Misra is the best '

In [114]:
# Print the string for 3 times
3 * " Michael Jackson"

' Michael Jackson Michael Jackson Michael Jackson'

In [116]:
# Concatenate strings
name = "Soumendra Ranjan Misra"
Name = name + " is the best"
Name

'Soumendra Ranjan Misra is the best'

## ESCAPE SEQUENCES
Back slashes represent the begining of escape sequences. Escape sequences represent strings that may be difficult to input. For example, back slash "n"represents a new line. The output is given by a new line after the back slash "n" is encountered:

In [117]:
# New line escape sequence
print("Michael Jackson \n is the best")

Michael Jackson 
 is the best


In [118]:
# Tab escape sequence
print(" Michael jackson \t is the best")

 Michael jackson 	 is the best


In [119]:
# Include back slash in string
print(" soumendra Ranjan Misra \\ is the best")

 soumendra Ranjan Misra \ is the best


In [121]:
# r will tell python that string will be display as raw string
print(r" soumendra Ranjan Misra \ is the best")

 soumendra Ranjan Misra \ is the best


## STRING OPERATIONS

In [122]:
# Convert all the characters in string to upper case
A = "My name is Soumendra ranjan misra"
print("before upper:", A)

before upper: My name is Soumendra ranjan misra


In [124]:
B = A.upper()
print("After upper:",B)

After upper: MY NAME IS SOUMENDRA RANJAN MISRA


In [126]:
# Replace the old substring with the new target substring is the segment has been found in the string
A = "Michael Jackson is the best"
B = A.replace('Michael', 'soumendra')
B

'soumendra Jackson is the best'

## FINDS a sub-string

In [128]:
# Find the substring in the string. Only the index of the first element of substring in string will be the output
Name = "Soumendra ranjan misra"
Name.find('od')

-1

In [129]:
Name.find('misra')

17

In [133]:
# Write your code below code below and press shift + Enter to execute
F = "You are wrong"
F.upper()

'YOU ARE WRONG'

In [134]:
# Write your code  below and press shift+enter to execute
G = "Mary had a little lamb little lamb, little lamb Mary had a little lamb \
Its fleece was white as snow And everywhere that Mary went Mary went, Mary went \
Everywhere that Mary went The lamb was sure to go"
G.find("snow")

95

## TUPLES

In [136]:
# Create your first tuple

tuple1 = ("disco",10, 1.2)
tuple1

('disco', 10, 1.2)

In [137]:
# Print the type of the tuple you created
type(tuple1)

tuple

# PYTHON NUMPY

In [138]:
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]
speed=[10,20,30,40]

In [139]:
import numpy as np

In [140]:
np_distance = np.array(distance)
np_time=np.array(time)
np_speed=np.array(speed)

In [147]:
speed=np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

# Create and NumPy array

In [149]:
#import Numpy library
import numpy as np

In [150]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [151]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [152]:
#array with zeros
array_with_zeros= np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [153]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [158]:
#array with empty
array_with_empty = np.empty((3,4))
array_with_empty

array([[1.22468221e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.31452438e-047, 2.61068224e-057,
        9.74590074e-072],
       [9.97518545e-047, 1.09733523e-071, 4.11772209e-033,
        3.13999977e-032]])

In [162]:
#array with arange method
np_arange = np.arange(12)

In [163]:
#print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [165]:
#reshape method to change / create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)

In [168]:
#print linsspaced array
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [169]:
#One dimensional array
oneD_array = np.arange(15)

In [170]:
#print 1D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [173]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)

In [174]:
#print two dimensional array
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [175]:
# 3D array
ThreeD_array = np.arange(27).reshape(3,3,3)

In [176]:
# Print 3D array
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [177]:
np_city = np.array(['NYC', 'LA','Miami','Houston'])

In [178]:
np_city.ndim

1

In [179]:
np_city_with_state = np.array([['NYC','LA','Miami','Houston'],['NY', 'CA', 'FL', 'TX']])

In [180]:
np_city_with_state.ndim

2

In [181]:
np_city = np.array(['NYC', 'LA', 'Miami', 'Houston'])

In [182]:
np_city_with_state = np.array([['NYC', 'LA', 'Miami', 'Houston'],['NY','CA', 'FL', 'TX']])

In [183]:
np_city.shape

(4,)

In [184]:
np_city_with_state.shape

(2, 4)

In [185]:
np_city.shape

(4,)

In [186]:
np_city_with_state.shape

(2, 4)

In [187]:
np_city.size

4

In [188]:
np_city_with_state.size

8

In [189]:
np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [190]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

In [191]:
np_city_with_state.dtype

dtype('<U7')

In [192]:
first_trial_cyclist =[10,15,17,26]

In [193]:
second_trial_cyclist =[12,11,21,24]

In [198]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [199]:
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','staten Island','Queens'])

In [200]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Queens'],
      dtype='<U13')

In [201]:
Boroughs_in_NYC = NYC_Borough

In [202]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Queens'],
      dtype='<U13')

In [203]:
Boroughs_in_NYC is NYC_Borough

True

In [204]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Queens'],
      dtype='<U13')

In [205]:
Boroughs_in_NYC = Boroughs_in_NYC.view()

In [209]:
len(Boroughs_in_NYC)

5

In [211]:
Boroughs_in_NYC[4] ='Central Park'

In [212]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [213]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [214]:
Copy_of_NYC_Borough = NYC_Borough.copy()

In [215]:
Copy_of_NYC_Borough is NYC_Borough

False

In [216]:
Copy_of_NYC_Borough.base is NYC_Borough

False

In [217]:
Copy_of_NYC_Borough[4]='Central Park'

In [218]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [220]:
Copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

# ASSIGNMENT (GDP ASSUMPTION)

In [223]:
#Analyze gdp per capita for given set of countries
#find country with max and min gdp
#find and print gdp per capita of each country
#print gdp => mean, max, min,standard deviation and sum
import numpy as np
countries = np.array(['Algeria','Angolia','Argentina','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil',
                     'Bulgaria','Cambodia','Cameroon','chile','china','columbia','Cyprus','Denmark','El Salvadoor','Estonia'
                     ,'Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Hondures','Hungry','India'
                     'Indonesia','Ireland','Italy','Japan','Kenya','south korea','Liberia','Malaysia','Mexico','Morocco','Nepal','New Zealand'
                     ,'Norway','Pakistan','Peru','Qatar','Russia','Singapore','South Africa','Spain','sweden','switzerland','Thailand',
                     'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuala','Vietnam','Zimbabwe'])
gdp_per_capita = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,
                          24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,
                          3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,
                          23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,
                          837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.22044061,
                          5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,
                          36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,
                          21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])


In [224]:
max_gdp_per_capita = gdp_per_capita.argmax()

In [225]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]

In [235]:
country_with_max_gdp_per_capita

'Peru'

In [236]:
min_gdp_per_capita = gdp_per_capita.argmin()

In [237]:
country_with_min_gdp_per_capita = countries[min_gdp_per_capita]

In [238]:
country_with_min_gdp_per_capita

'Fiji'

In [239]:
for country in countries:
    print('ecaluating country{}', format(country))

ecaluating country{} Algeria
ecaluating country{} Angolia
ecaluating country{} Argentina
ecaluating country{} Austria
ecaluating country{} Bahamas
ecaluating country{} Bangladesh
ecaluating country{} Belarus
ecaluating country{} Belgium
ecaluating country{} Bhutan
ecaluating country{} Brazil
ecaluating country{} Bulgaria
ecaluating country{} Cambodia
ecaluating country{} Cameroon
ecaluating country{} chile
ecaluating country{} china
ecaluating country{} columbia
ecaluating country{} Cyprus
ecaluating country{} Denmark
ecaluating country{} El Salvadoor
ecaluating country{} Estonia
ecaluating country{} Ethiopia
ecaluating country{} Fiji
ecaluating country{} Finland
ecaluating country{} France
ecaluating country{} Georgia
ecaluating country{} Ghana
ecaluating country{} Grenada
ecaluating country{} Guinea
ecaluating country{} Haiti
ecaluating country{} Hondures
ecaluating country{} Hungry
ecaluating country{} IndiaIndonesia
ecaluating country{} Ireland
ecaluating country{} Italy
ecaluating

In [242]:
for i in range(len(countries)):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print('country {}  per capita gdp is {}'.format(country,country_gdp_per_capita))

country Algeria  per capita gdp is 2255.225482
country Angolia  per capita gdp is 629.9553062
country Argentina  per capita gdp is 11601.63022
country Austria  per capita gdp is 25306.82494
country Bahamas  per capita gdp is 27266.40335
country Bangladesh  per capita gdp is 19466.99052
country Belarus  per capita gdp is 588.3691778
country Belgium  per capita gdp is 2890.345675
country Bhutan  per capita gdp is 24733.62696
country Brazil  per capita gdp is 1445.760002
country Bulgaria  per capita gdp is 4803.398244
country Cambodia  per capita gdp is 2618.876037
country Cameroon  per capita gdp is 590.4521124
country chile  per capita gdp is 665.7982328
country china  per capita gdp is 7122.938458
country columbia  per capita gdp is 2639.54156
country Cyprus  per capita gdp is 3362.4656
country Denmark  per capita gdp is 15378.16704
country El Salvadoor  per capita gdp is 30860.12808
country Estonia  per capita gdp is 2579.115607
country Ethiopia  per capita gdp is 6525.541272
country 

In [243]:
print(gdp_per_capita.max())
print(gdp_per_capita.min())
print(gdp_per_capita.mean())
print(gdp_per_capita.std())
print(gdp_per_capita.sum())

40034.85063
229.6769525
11289.409272187462
12743.828910144688
711232.7841478101


# GOLD ASSIGNMENT

In [244]:
# import necessary Libraries
import numpy as np

In [247]:
#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR', 'China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,14])

## Find country with maximum gold

In [248]:
#find country index with maximum gold
max_gold_index = np_olympic_country_Gold.argmax()

In [249]:
country_with_max_gold = np_olympic_country[max_gold_index]

In [250]:
country_with_max_gold

'US'

## Find countries with more than 20 gold medals

In [251]:
#country won more than 20 gold medals, use boolean indexing technique
print(np_olympic_country[np_olympic_country_Gold>20])

['GBR' 'China' 'RUS' 'US']


## Evaluate the dataset and print the medal tally


In [263]:
#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR', 'China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,14,21])

In [264]:
#print each country name with number of gold medals
#print each country name with total number of medals
for i in range(len(np_olympic_country)):
    gold_medal = np_olympic_country_Gold[i]
    country = np_olympic_country[i]
    total_medal = np_olympic_country_Bronze[i]+np_olympic_country_Gold[i]+np_olympic_country_Silver[i]
    print('{}, gold medal {}, Total medals {}'.format(country,gold_medal,total_medal))

GBR, gold medal 29, Total medals 65
China, gold medal 38, Total medals 88
RUS, gold medal 24, Total medals 81
US, gold medal 46, Total medals 103
KOR, gold medal 13, Total medals 28
JPN, gold medal 7, Total medals 35
GER, gold medal 11, Total medals 43
