# NUMPY

In [1]:
import numpy as np

In [2]:
#LIST OF INTEGERS
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
type(L[0])

int

In [5]:
# LIST OF STRINGS
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

In [17]:
list = [1,2,3,4,5,6]
list

[1, 2, 3, 4, 5, 6]

In [21]:
#CREATING HETEROGENOUS LIST
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### CREATING ARRAYS FROM PYTHON LISTS

In [25]:
# integer array:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [26]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [30]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [31]:
# nested lists result in multidimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### CREATING ARRAYS FROM SCRATCH

In [32]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# Create a 3X5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [36]:
#Create an array filled with a linear sequence
#Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
#Create a 3X3 array of uniformly distributed
#random values 0 and 1
np.random.random((3,3))

array([[0.07562017, 0.6606284 , 0.75714786],
       [0.18160305, 0.13445252, 0.81603576],
       [0.09363776, 0.08437955, 0.44297256]])

In [41]:
#Create a 3X3 array of normally distributed random values
#with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.01478164,  1.19535673, -0.45616578],
       [ 0.22284801,  1.91010462,  0.29139869],
       [-0.53898237, -0.43849818, -0.61858973]])

In [42]:
# Create a 3X3 array of random integers in the interval [0, 10)
np.random.randint(0,10, (3,3))

array([[1, 2, 1],
       [0, 9, 5],
       [7, 0, 3]])

In [43]:
# Create a 3X3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Array Attributes

In [46]:
import numpy as np
np.random.seed(0) # seed for reproductivity
x1 = np.random.randint(10, size=6) #One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #Three-dimensional array

In [47]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [48]:
print("dtype:", x3.dtype)

dtype: int32


In [49]:
# items size
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [ ]:
# Array Indexing: Accessing Single elements

In [52]:
x1

array([5, 0, 3, 3, 7, 9])

In [51]:
x1[0]

5

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [56]:
x1[4]

7

In [57]:
x1[-1]

9

In [58]:
x1[-2]

7

In [59]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [60]:
x2[0,0]

3

In [61]:
x2[2,0]

1

In [62]:
x2[2,-1]

7

In [63]:
# MODIFYING VALUES USING ANY OF THE ABOVE INDEX

In [64]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [65]:
x1[0] = 3.14159 # this will truncated!
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing:Accessing Subarrays

In [67]:
# One dimensional subarrays

In [69]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# first five elements
x[:5 ]

array([0, 1, 2, 3, 4])

In [73]:
# middle subarray
x[4:7]

array([4, 5, 6])

In [74]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [75]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [76]:
# all elements, reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
# reversed every other from index 5
x[5::-2]

array([5, 3, 1])

### MULTIDIMENSIONAL ARRAYS

In [89]:
# Multidimensional slices
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [90]:
# two rows, three columns
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [91]:
# all rows, every other column
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [92]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [93]:
# first column of x2
print(x2[:, 0])

[12  7  1]


In [94]:
# first row of x2
print(x2[0, :])

[12  5  2  4]


In [95]:
# equivalent to x2[0, :]
print(x2[0])

[12  5  2  4]


## Subarrays as no-copy views

In [96]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [97]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [98]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Creating copies of arrays

In [88]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [99]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [100]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [101]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
#row vector via reshape
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [103]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [104]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [105]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# ARRAY CONCATENATION AND SPLITTING

In [106]:
#Concatenation of arrays

In [107]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [109]:
# Concatenating more than two arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [112]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [113]:
# concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [114]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [117]:
# vertically stack the arrays
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [120]:
# horizontally stack the arrays
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## SPLITTING OF ARRAYS

In [121]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [122]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [124]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### ABSOLUTE VALUE

In [126]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [127]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [131]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [133]:
x = np.array([3 -4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### TRIGONOMETRIC FUNCTIONS

In [134]:
theta = np.linspace(0, np.pi, 3)

In [135]:
print("theta  =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta  = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [136]:
x = [-1, 0, 1]
print("x           =", x)
print("arcsin(x)   =", np.arcsin(x))
print("arccos(x)   =", np.arccos(x))
print("arctan(x)   =", np.arctan(x))

x           = [-1, 0, 1]
arcsin(x)   = [-1.57079633  0.          1.57079633]
arccos(x)   = [3.14159265 1.57079633 0.        ]
arctan(x)   = [-0.78539816  0.          0.78539816]


### EXPONENTS AND LOGARITHMS

In [137]:
x = [1,2,3]
print("x       =", x)
print("e^x     =", np.exp(x))
print("2^x     =", np.exp2(x))
print("3^x     =", np.power(3, x))

x       = [1, 2, 3]
e^x     = [ 2.71828183  7.3890561  20.08553692]
2^x     = [2. 4. 8.]
3^x     = [ 3  9 27]


In [139]:
x = [1,2,4, 10]
print("x       =", x)
print("ln(x)   =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x)=", np.log10(x))

x       = [1, 2, 4, 10]
ln(x)   = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


In [140]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


### AGGREGATIONS: Min, Max, and Everything in Between

In [149]:
#Summing the values in an array
import numpy as np

In [150]:
L = np.random.random(100)
sum(L)

49.78278912531625

In [146]:
np.sum(L)

52.12818058833702

In [144]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

175 ms ± 5.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.64 ms ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### MINIMUM AND MAXIMUM

In [151]:
min(big_array), max(big_array)

(1.4057692298008462e-06, 0.9999994392723005)

In [152]:
np.min(big_array), np.max(big_array)

(1.4057692298008462e-06, 0.9999994392723005)

In [153]:
%timeit min(big_array)
%timeit np.min(big_array)

138 ms ± 7.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
749 µs ± 25.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [154]:
print(big_array.min(), big_array.max(), big_array.sum())

1.4057692298008462e-06 0.9999994392723005 500202.5348847683


### MULTIDIMENSIONAL AGGREGATES

In [155]:
M = np.random.random((3, 4))
print(M)

[[0.40002294 0.94781851 0.6296097  0.65183099]
 [0.91883046 0.51964276 0.96072317 0.87860829]
 [0.90054149 0.73546657 0.76402889 0.63463004]]


In [156]:
M.sum()

8.941753800245062

In [157]:
M.min(axis=0)

array([0.40002294, 0.51964276, 0.6296097 , 0.63463004])

In [158]:
M.max(axis=1)

array([0.94781851, 0.96072317, 0.90054149])

In [163]:
import pandas as pd
data = pd.read_csv('C:\\Users\\Parul\\Desktop\\DATASETS\\bank.csv')