## CLASS AND OBJECT

In [1]:
# Define Class
class SHARK:
    def swim(self):
        print("SHARK is swimming")
        
    def be_awesome(self):
        print("SHARK is being awesome")

In [2]:
# Create object
dobby = SHARK()

In [3]:
# Access
dobby.swim()

SHARK is swimming


In [4]:
dobby.be_awesome()

SHARK is being awesome


In [5]:
help (SHARK())

Help on SHARK in module __main__ object:

class SHARK(builtins.object)
 |  Methods defined here:
 |  
 |  be_awesome(self)
 |  
 |  swim(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



CONSTRUCTOR(create any object) AND DESTRUCTOR(delete an object)

In [6]:
class vehicle:
    def __init__(self):
        print('Vehicle created, Constructor got called')
        
    def __del__(self):
        print("Destructor called, vehicle deleted.")

In [7]:
truck = vehicle()

Vehicle created, Constructor got called


In [8]:
del truck

Destructor called, vehicle deleted.


## NUMPY BASIC

In [9]:
import numpy as np

In [10]:
myList = [1,2,3]
print(myList)
type(myList)

[1, 2, 3]


list

In [11]:
arr = np.array(myList)
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [12]:
list_mul = myList * 2
list_mul

[1, 2, 3, 1, 2, 3]

In [13]:
arr_mul = arr * 2
arr_mul

array([2, 4, 6])

In [14]:
myTuple = (1,2,3)
print(myTuple)
type(myTuple)

(1, 2, 3)


tuple

In [15]:
arr_tuple = np.array(myTuple)
print(arr_tuple)
type(arr_tuple)

[1 2 3]


numpy.ndarray

In [16]:
#Tuple of array dimension
arr2 = np.array([(1,2,3),(4,5,6)])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2.ndim

2

In [18]:
#List of array dimension
list1 = [1,2,3]
list2 = [4,5,6]
new_arr = np.array([list1,list2])
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
new_arr.ndim #to check dimension

2

In [20]:
new_arr.itemsize

4

In [21]:
#No of elements
new_arr.size

6

In [22]:
#To check the datatype
new_arr.dtype

dtype('int32')

In [23]:
#shape
new_arr.shape

(2, 3)

In [24]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#Reshaping arrays
new_arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#Transpose an array(only on array as .T is a function of numpy)
new_arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.transpose(new_arr) # this will work on tuple , list, array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
arr

array([1, 2, 3])

In [31]:
#Accessing array values
arr[1]

2

In [32]:
arr[2]

3

In [33]:
arr[0]

1

In [34]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
new_arr[0,1]

2

In [36]:
new_arr[1,2]

6

In [37]:
new_arr[0,2]

3

In [38]:
#Iterate index values
new_arr[0:,2]

array([3, 6])

In [39]:
new_arr[1:,2]

array([6])

In [40]:
new_arr[:,1]

array([2, 5])

In [41]:
new_arr[:,2]

array([3, 6])

In [42]:
new_arr[2:,2]

array([], dtype=int32)

In [43]:
n_arr = np.array([(1,2),(3,4),(5,6),(7,8)])
print(n_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
n_arr[0:,1]

array([2, 4, 6, 8])

In [45]:
n_arr[0:2,1]

array([2, 4])

In [46]:
n_arr[0:1,1]

array([2])

In [47]:
n_arr[0:3,1]

array([2, 4, 6])

In [48]:
n_arr[1:3,1]

array([4, 6])

In [49]:
n_arr[1:3]

array([[3, 4],
       [5, 6]])

In [50]:
n_arr[1:2]

array([[3, 4]])

In [51]:
n_arr[1]

array([3, 4])

In [52]:
#Fetching evenly spaced numbers over a specified interval
e_val = np.linspace(1,3,20)
e_val

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [53]:
# Fetch min value
print(arr)
arr.min()

[1 2 3]


1

In [54]:
# Fetch max value
arr.max()

3

In [55]:
# Sum of values in an array
print(arr)
arr.sum()

[1 2 3]


6

In [56]:
print(new_arr)
print("Sum of all the values:",new_arr.sum())
print("Sum of row values: ",new_arr.sum(axis=1))
print("Sum of column values: ",new_arr.sum(axis=0))

[[1 2 3]
 [4 5 6]]
Sum of all the values: 21
Sum of row values:  [ 6 15]
Sum of column values:  [5 7 9]


In [57]:
help(new_arr.sum)

Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False)
    
    Return the sum of the array elements over the given axis.
    
    Refer to `numpy.sum` for full documentation.
    
    See Also
    --------
    numpy.sum : equivalent function



In [58]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
#Getting the aquare root of all the values
np.sqrt(new_arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [60]:
#To get the square of all the values
new_arr**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [61]:
#Addition of multiple array elements
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(4,5,6)])
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [62]:
#Subtraction of multiple array elements
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
#Multiplication of multiple array elements
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [65]:
#Stack arrays - Vertical Stacking
arr1 = np.array([(1,2,3),(4,5,6)])
arr1 = np.array([(1,2,3),(4,5,6)])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
#Horizontal Stacking
np.hstack((arr1,arr2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
np.ones(10).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])